//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DungeonExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DungeonExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Items&gt;
        ///  &lt;Weapons&gt;
        ///    &lt;GreatSword&gt;
        ///      &lt;name&gt;GreatSword&lt;/name&gt;
        ///      &lt;hands&gt;2&lt;/hands&gt;
        ///      &lt;baseDamage&gt;16&lt;/baseDamage&gt;
        ///      &lt;critChange&gt;10&lt;/critChange&gt;
        ///      &lt;critMultiply&gt;2&lt;/critMultiply&gt;
        ///    &lt;/GreatSword&gt;
        ///    &lt;prefix&gt;
        ///      &lt;fire&gt;
        ///        &lt;flaming&gt;
        ///          &lt;name&gt;flaming&lt;/name&gt;
        ///          &lt;damage&gt;1d6&lt;/damage&gt;
        ///          &lt;type&gt;fire&lt;/type&gt;
        ///        &lt;/flaming&gt;
        ///      &lt;/fire&gt;
        ///      &lt;ice&gt;
        ///        &lt;frost&gt;
        ///          &lt;name&gt;frost&lt;/name&gt;
        ///          &lt;dama [rest of string was truncated]&quot;;.
        /// </summary>
        public static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Maps&gt;
        ///  &lt;Map&gt;
        ///    &lt;Id&gt;0&lt;/Id&gt;
        ///    &lt;Name&gt;Blank&lt;/Name&gt;
        ///    &lt;Chest&gt;false&lt;/Chest&gt;
        ///    &lt;Blocked&gt;0&lt;/Blocked&gt;
        ///    &lt;Msg&gt;Don&apos;t change this&lt;/Msg&gt;
        ///  &lt;/Map&gt;
        ///  &lt;Map&gt;
        ///    &lt;Id&gt;1&lt;/Id&gt;
        ///    &lt;Name&gt;Home&lt;/Name&gt;
        ///    &lt;Chest&gt;false&lt;/Chest&gt;
        ///    &lt;Blocked&gt;2&lt;/Blocked&gt;
        ///    &lt;Msg&gt;
        ///      You find your self in a locked cellar in a dungeon.
        ///      Please choose your action.
        ///      (You can type HELP for your commands list).
        ///    &lt;/Msg&gt;
        ///  &lt;/Map&gt;
        ///  &lt;Map&gt;
        ///    &lt;Id&gt;2&lt;/Id&gt;
        ///    &lt;Name&gt;Home2&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string maps {
            get {
                return ResourceManager.GetString("maps", resourceCulture);
            }
        }
    }
}
